#!/bin/sh
# xraystyle's Remote Management Fix https://github.com/xraystyle/apple-remote-management-fix

set -e


if [ -f '/private/etc/RemoteManagement.launchd' ]; then
	# do nothing
	`syslog -s -l error "Remote Management is currently enabled."`
	exit 0
else

	`syslog -s -l error "Change detected in /private/etc/RemoteManagement.launchd"`

	/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -access -on -privs -all -users ADMINACCT

	/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate

	`syslog -s -l error "Remote Management re-activated."` 
fi

exit 0